styles = [
    '8-bit',
    'acoustic',
    'adult contemporary',
    'alternative',
    'ambient',
    'americana',
    'avant-garde',
    'ballad',
    'big band',
    'black metal',
    'bluegrass',
    'blues',
    'bossa nova',
    'celtic',
    'chanson',
    'christian',
    'classic rock',
    'classical',
    'club',
    'comedy',
    'country',
    'dance',
    'dark wave',
    'death metal',
    'disco',
    'drum and bass',
    'dub',
    'electronic',
    'electronica',
    'electropop',
    'emo',
    'experimental',
    'female volcalists',
    'folk',
    'funk',
    'fusion',
    'glitch',
    'gospel',
    'gothic',
    'grunge',
    'guitar virtuoso',
    'gypsy',
    'hardcore',
    'heavy metal',
    'hip hop',
    'house',
    'indie',
    'industrial',
    'instrumental',
    'j-pop',
    'j-rock',
    'jazz',
    'kpop',
    'latin',
    'lo-fi',
    'lounge',
    'male vocalist',
    'mediaeval',
    'metal',
    'minmimal',
    'motown',
    'musical',
    'new wave',
    'noise',
    'old school',
    'opera',
    'pop',
    'psychedelic',
    'punk',
    'r&amp;b',
    'rap',
    'reggae',
    'rock',
    'romantic',
    'roots',
    'singer-songwriter',
    'ska',
    'soul',
    'soundtrack',
    'style',
    'surf music',
    'swing',
    'symphonic',
    'tango',
    'techno',
    'trance',
    'trip hop',
    'turnablism',
    'world',
    'worship music'
]

moods = [
    'aggressive',
    'ambient',
    'angry',
    'angst-ridden',
    'bouncy',
    'calming',
    'carefree',
    'cheerful',
    'cold',
    'complex',
    'cool',
    'dark',
    'disturbing',
    'dramatic',
    'dreamy',
    'eerie',
    'elegant',
    'energetic',
    'enthusiastic',
    'epic',
    'fun',
    'funky',
    'futuristic',
    'gentle',
    'gleeful',
    'gloomy',
    'groovy',
    'happy',
    'harsh',
    'haunting',
    'humorous',
    'hypnotic',
    'industrial',
    'intense',
    'intimate',
    'joyous',
    'laid-back',
    'light',
    'lively',
    'manic',
    'meditation',
    'melancholia',
    'mellow',
    'mystical',
    'ominous',
    'party music',
    'passionate',
    'pastoral',
    'peaceful',
    'playful',
    'poignant',
    'quiet',
    'rebellious',
    'reflective',
    'relax',
    'romantic',
    'rowdy',
    'sad',
    'sentimental',
    'sexy',
    'smooth',
    'soothing',
    'sophisticated',
    'spacey',
    'spiritual',
    'strange',
    'sweet',
    'theater',
    'trippy',
    'warm',
    'whimsical'
]
